server:
    port: 8888

app:
    api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: notification_service
          uri: http://localhost:8082
          predicates:
          - Path=${app.api-prefix}/notification/**
          filters:
          - StripPrefix=2



