version: '3.8'
services:
  mysqldb:
    image: mariadb:10.6
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spring_security_jwt
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - tiennguyendev

  user-service:
    build: .
    container_name: springboot-app
    restart: always
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mysqldb:3306/spring_security_jwt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    networks:
      - tiennguyendev

networks:
  tiennguyendev:
    driver: bridge