
services:
  inventory-service:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/inventoryDB
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo
    container_name: mongo_inventory
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
